### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by ahives**

### CODE REVIEW

**Comment by phatboyg** [comment]
Some of these changes aren't good ones, such as throwing an exception in the HL7MessageParser - that would cause issues parsing a stream of messages since the first would be fine and then it would throw an exception, am I right?

**Comment by ahives** [comment]
I think this is ok because if it can't parse the MSH segment and load the delimiters into memory then attempting to parse after that is useless. This is consistent with how the X12 parser works with ISA. Unless we make a point to hard code the delimiters and not worry about the MSH segment altogether.

**Comment by phatboyg** [comment]
But this is for parsing a stream of messages, right?

It should just return Unmatched after the first matching message, instead of throwing an exception.

**Comment by ahives** [comment]
Hmm, you are partially correct. It gets called for both and maybe that is the problem. For stream this might be bad but the question is that for stream parsing do we retain knowledge of the delimiters? If we do then it is a useless check for both, which means we probably should just hard code the delimiters.

**Comment by ahives** [comment]
That said, if I have a malformed message that was discovered on the first read then why would I want to continue parsing? Moreover, why would that be considered a successful parse if I find the data I am looking for downstream on a malformed message?

**Comment by ahives** [comment]
Easy revert for me but I still think those are valid concerns. I will create a issue to further the discussion.

**Pull request merged**
